name: Java CI with Maven - Test and package
 
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm_version:
          - '21'

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'corretto'
        java-version: ${{ matrix.jvm_version }}

    # - name: Build and Test with Maven
    #   timeout-minutes: 15
    #   run: |
    #     mvn -B package

    - name: Sonar cube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')

# UdeM-DIRO-IFT3913
    # - name: Get JaCoCo Coverage
    #   id: coverage  
    #   run: |
    #     coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
    #     echo "COVERAGE=$coverage" >> $GITHUB_ENV

    # - name: Fail if coverage has decreased
    #   run: |
    #     coverage=$COVERAGE
    #     threshold=27.33
    #     echo "Flags : '$MAVEN_OPTS'"
    #     echo "Coverage attendu : $threshold%"
    #     if (( $(echo "$coverage < $threshold" | bc -l) )); then
    #       echo "Coverage has decreased ($coverage%) !!!"
    #       exit 1
    #     else
    #       echo "Coverage is still!"
    #     fi

